name: Build Tomcat

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - name: github_env
    #   run: |
    #       echo "GITHUB_WORKFLOW: ${{ GITHUB_WORKFLOW }}"
    #       echo "GITHUB_ACTION: ${{ GITHUB_ACTION }}"
    #       echo "GITHUB_ACTOR: ${{ GITHUB_ACTOR }}"
    #       echo "GITHUB_REPOSITORY: ${{ GITHUB_REPOSITORY }}"
    #       echo "GITHUB_EVENT_NAME: ${{ GITHUB_EVENT_NAME }}"
    #       echo "GITHUB_EVENT_PATH: ${{ GITHUB_EVENT_PATH }}"
    #       echo "GITHUB_WORKSPACE: ${{ GITHUB_WORKSPACE }}"
    #       echo "HOME: ${{ HOME }}"
          
    - name: Check out tomcat-users.xml
      uses: actions/checkout@v4

    - name: List project files and java version
      run: |
          ls -ltr
          java -version
          

    - name: Check out Apache Tomcat
      uses: actions/checkout@v4
      with:
        repository: apache/tomcat # Repository name with owner
        ref: main               # The branch, tag or SHA to checkout
        path: ./tomcat            # Relative path under $GITHUB_WORKSPACE

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        check-latest: true

        
    - name: List project files and java version
      run: |
          ls -ltr
          java -version

    - name: Copy tomcat-users.xml into Tomcat configuration directory
      run: cp -v tomcat-users.xml ./tomcat/conf/tomcat-users.xml

    - name: Compile Tomcat
      run: |
        cd ./tomcat
        ant
